### NUMPY

Numpy, open source python package for numerical computation. 

- Its faster and less compact than python lists.
- It consumes less memory.

In [1]:
import numpy as np

#### Data types

In [2]:
# Creating a float
x = np.float64(1.2567)
x

1.2567

In [3]:
type(x)

numpy.float64

In [4]:
w = np.int64(1.2222)
w

1

In [5]:
type(w)

numpy.int64

#### Numpy Arrays
Multidimentional array-like data structure

Creating the arrays

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Convert Python List to a Numpy Array

In [9]:
scores = [50,60,70,24,55,40]

In [10]:
scores_array = np.array(scores)

#Checking the type
type(scores_array)

numpy.ndarray

In [11]:
#Checking the dimension of the array
scores_array.ndim

1

In [12]:
#Checking thr number of items in the array
scores_array.size

6

In [13]:
#Checking the datatype
scores_array.dtype

dtype('int32')

In [14]:
#Print unique values
np.unique(scores_array)

array([24, 40, 50, 55, 60, 70])

In [15]:
scores_array

array([50, 60, 70, 24, 55, 40])

In [16]:
#Reversing the array
np.flip(scores_array)

array([40, 55, 24, 70, 60, 50])

In [17]:
#Sorting the array

np.sort(scores_array)

array([24, 40, 50, 55, 60, 70])

In [18]:
scores_array

array([50, 60, 70, 24, 55, 40])

In [19]:
#return vlaues in a certain range
np.clip(scores_array,20,59)

array([50, 59, 59, 24, 55, 40])

Joining two arrays

In [20]:
array_two = np.array([90,26,37,77,65,55])

In [21]:
np.concatenate((scores_array,array_two))

array([50, 60, 70, 24, 55, 40, 90, 26, 37, 77, 65, 55])

Creating arrays

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Creating an identity matrix

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

np.linspace()

This returns evenly spaced numbers over a specified interval with a start, stop and a step value.

In [27]:
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [29]:
np.linspace(10,15,5)

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

Creating an array of the given shape and populate it with random samples from a uniform distribution

In [32]:
np.random.rand(10)

array([0.48025422, 0.10969411, 0.81907766, 0.34278364, 0.59422137,
       0.48681229, 0.13841818, 0.32109694, 0.15582965, 0.46674611])

In [31]:
np.random.rand(3,2)

array([[0.32663864, 0.18697261],
       [0.78704007, 0.87813535],
       [0.03486155, 0.33726127]])

In [33]:
np.random.randint(15)

14

In [35]:
np.random.randint(5,20,6) #return random integers from low (inclusive) to hight (exclusive)

array([ 5, 18,  7,  5,  6, 19])

In [37]:
np.array([np.nan,6,np.nan]) # nan is returned when a number does not exist

array([nan,  6., nan])

Checking documentation

In [39]:
help(np.linspace) #  or np.linspace?

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, s

Indexing and Broadcasting in Numpy

Indexing for a 1 dimentional array

In [45]:
matrix = np.arange(1,17)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [46]:
matrix[0]

1

In [47]:
matrix[2:6]

array([3, 4, 5, 6])

In [48]:
matrix[12:]

array([13, 14, 15, 16])

Indexing for a 2 dimentional array

In [50]:
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [52]:
matrix.size

16

In [59]:
matrix = matrix.reshape(4,4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
matrix[0]

array([1, 2, 3, 4])

In [61]:
matrix[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
matrix[1:3,1:3] # Get values 6,7,10,11

array([[ 6,  7],
       [10, 11]])

In [67]:
matrix[2:4,1:2] # Get values 10 and 14

array([[10],
       [14]])

In [70]:
matrix[2:4,2:4]  # Get 11,12,15,16 ; rows first thern columns(indexing)

array([[11, 12],
       [15, 16]])

Broadcasting in numpy

In [71]:
scores = [50,60,70,30,25]

In [76]:
# To create a numpy array

scores_array = np.array(scores)
scores_array

array([50, 60, 70, 30, 25])

In [79]:
# Change 50,60,70 to 20,40,90 (BROADCASTING)

scores_array[0:3] = [20,40,90]
scores_array

array([20, 40, 90, 30, 25])

NUMPY OPERATIONS

In [86]:
matrix = np.arange(17,33)

In [88]:
matrix = matrix.reshape(4,4)
matrix

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [89]:
matrix.shape

(4, 4)

In [90]:
matrix.ndim

2

In [91]:
np.max(matrix)

32

In [93]:
np.max(matrix)

32

In [94]:
np.argmax(matrix)

15

In [96]:
np.min(matrix)

17

In [97]:
np.argmin(matrix)

0

In [95]:
np.sum(matrix)

392

In [99]:
np.sqrt(matrix)

array([[4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262],
       [5.38516481, 5.47722558, 5.56776436, 5.65685425]])

In [100]:
np.transpose(matrix)

array([[17, 21, 25, 29],
       [18, 22, 26, 30],
       [19, 23, 27, 31],
       [20, 24, 28, 32]])

In [101]:
matrix

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [102]:
matrix.flatten()

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [103]:
matrix.ravel()

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [104]:
matrix2 = np.arange(1,17)

In [106]:
matrix2 = matrix2.reshape(4,4)
matrix2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [107]:
matrix + matrix2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [108]:
matrix * matrix2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

In [109]:
matrix / matrix2

array([[17.        ,  9.        ,  6.33333333,  5.        ],
       [ 4.2       ,  3.66666667,  3.28571429,  3.        ],
       [ 2.77777778,  2.6       ,  2.45454545,  2.33333333],
       [ 2.23076923,  2.14285714,  2.06666667,  2.        ]])

In [110]:
matrix % matrix2

array([[0, 0, 1, 0],
       [1, 4, 2, 0],
       [7, 6, 5, 4],
       [3, 2, 1, 0]])